version: '3'

services:
  postgres:
    container_name: matchub-postgres
    image: 'postgres:15'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data/
  
  adminer:
    container_name: matchub-adminer
    image: 'adminer:latest'
    ports:
      - '3645:3645'

volumes:
  postgres: