version: '3'

services:
  api:
    container_name: matchub-api
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - backend-services
    depends_on:
      - postgres

  postgres:
    container_name: matchub-postgres
    image: 'postgres:15'
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - backend-services

  adminer:
    container_name: matchub-adminer
    image: adminer:latest
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - backend-services

volumes:
  postgres:
  pgadmin:

networks:
  backend-services: